name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Extract parent image name
      id: extract_parent_image_name
      run: |
        FROM_LINE=$(grep '^FROM' Dockerfile)
        FROM_TAG=$(echo $FROM_LINE | awk '{print $2}')
        PARTS=(${FROM_TAG//\// })
        DOCKER_IMAGE_TAG="maxc0c0s/${PARTS[1]}"
        echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> "$GITHUB_OUTPUT"
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.extract_parent_image_name.outputs.DOCKER_IMAGE_TAG }}
